### ISSUE TITLE
missing include <cstdint> in pcsc-mock.hpp

### ISSUE THREAD

**Issue by zketas** [web-eid/libpcsc-mock#6]
gcc 13 moved some includes around and as a result is no longer transitively included [1]. Explicitly include it for uint{32,64}_t.

[1] https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes

**Comment by mrts** [comment]
Thank you for bringing this to our attention. We will address this issue in due time and make the necessary updates to maintain compatibility with the latest compiler versions. Feel free to submit a patch if this issue is holding you back or causing any inconvenience.
